export const LOCAIS = [
  {
    id: 1,
    nome: 'Shopping Iguatemi Bosque',
    tipo: 'Estabelecimento',
    bairro: 'Centro',
    nota: 5.0,
    criterios: ['Rampa', 'Elevador', 'Calcada'],
  },
  {
    id: 2,
    nome: 'Beira-Mar de Fortaleza',
    tipo: 'Rua',
    bairro: 'Zona Sul',
    nota: 4.8,
    criterios: ['Calcada', 'Sinalizacao'],
  },
  {
    id: 3,
    nome: 'Centro Dragao do Mar',
    tipo: 'Estabelecimento',
    bairro: 'Centro',
    nota: 4.7,
    criterios: ['Rampa', 'Sinalizacao'],
  },
  {
    id: 4,
    nome: 'Terminal Papicu',
    tipo: 'Predio',
    bairro: 'Zona Norte',
    nota: 4.5,
    criterios: ['Rampa', 'Calcada'],
  },
  {
    id: 5,
    nome: 'Parque do Coco',
    tipo: 'Praca',
    bairro: 'Zona Sul',
    nota: 4.4,
    criterios: ['Calcada', 'Elevador'],
  },
  {
    id: 6,
    nome: 'Praca do Ferreira',
    tipo: 'Praca',
    bairro: 'Centro',
    nota: 4.3,
    criterios: ['Calcada'],
  },
  {
    id: 7,
    nome: 'Vila do Mar',
    tipo: 'Rua',
    bairro: 'Zona Norte',
    nota: 4.2,
    criterios: ['Sinalizacao'],
  },
  {
    id: 8,
    nome: 'CUCA Mondubim',
    tipo: 'Estabelecimento',
    bairro: 'Zona Norte',
    nota: 4.1,
    criterios: ['Rampa'],
  },
];
